config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  resources :shops do
    resources :bills
  end

  resources :bills do
    resources :products
  end

  resources :products

end

app/models/bill.rb
class Bill < ActiveRecord::Base

  belongs_to :shop
  has_many :products

  validates :buy_date, presence: true

	def amount
		amount = 0
		for product in self.products
			amount += product.price
		end
		return amount
	end
end

app/models/product.rb
class Product < ActiveRecord::Base
	
  belongs_to :bill

  validates :name, presence: true, length: { minimum: 3 }
  validates :quantity, presence: true, :numericality => { :greater_than => 0 }
  validates :quantity_type, presence: true
  validates :price, presence: true, :numericality => { :greater_than => 0 }
end

app/models/shop.rb
class Shop < ActiveRecord::Base

	has_many :bills

	validates :name, presence: true, length: { minimum: 3 }

	
	def amount
		amount = 0
		for bill in self.bills
			amount += bill.amount
		end
		return amount
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
	
	def index

		if params[:shop_id]
			@bills = Shop.find(params[:shop_id]).bills
		else
			@bills = Bill.all
		end

	end

	def show
		@bill = Bill.find(params[:id])
	end

	def new
		@bill = Bill.new
		@shops = Shop.all
	end

	def edit
		@bill = Bill.find(params[:id])
		@shops = Shop.all
	end

	def update
		@bill = Bill.find(params[:id])

		if @bill.update(bill_params)
			redirect_to bills_url
		else
			render 'edit'
		end
	end

	def create
		
		@bill = Bill.new(bill_params)
		
		if @bill.save
			redirect_to @bill
		else
			render 'new'
		end
	end

	def destroy
		@bill = Bill.find(params[:id])
		@bill.destroy

		redirect_to bills_path
	end

	private
		def bill_params
			params.require(:bill).permit(:name, :buy_date, :shop_id)
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	
	def index

		if params[:bill_id]
			@products = Bill.find(params[:bill_id]).products
		else
			@products = Product.all
		end

	end

	def show
		@product = Product.find(params[:id])
	end

	def new
		@product = Product.new
		@bills = Bill.all
	end

	def edit
		@product = Product.find(params[:id])
		@bills = Bill.all
	end

	def update
		@product = Product.find(params[:id])

		if @product.update(product_params)
			redirect_to products_url
		else
			render 'edit'
		end
	end

	def create
		
		@product = Product.new(product_params)
		
		if @product.save
			redirect_to @product
		else
			render 'new'
		end
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy

		redirect_to products_path
	end

	private
		def product_params
			params.require(:product).permit(:name, :quantity, :quantity_type, :price, :bill_id)
	end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
	
	def index
		@shops = Shop.all
	end

	def show
		@shop = Shop.find(params[:id])
	end

	def new
		@shop = Shop.new
	end

	def edit
		@shop = Shop.find(params[:id])
	end

	def update
		@shop = Shop.find(params[:id])

		if @shop.update(shop_params)
			redirect_to shops_url
		else
			render 'edit'
		end
	end

	def create
		
		@shop = Shop.new(shop_params)
		
		if @shop.save
			redirect_to @shop
		else
			render 'new'
		end
	end

	def destroy
		@shop = Shop.find(params[:id])
		@shop.destroy

		redirect_to shops_path
	end

	private
		def shop_params
			params.require(:shop).permit(:name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/bills/_form.html.erb
<%= form_for @bill do |f| %>
 
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@bill.errors.count, "error") %> prohibited
        this bill from being saved:
      </h2>
      <ul>
        <% @bill.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
  </p>

  <p>
    <%= f.label :buy_date %><br>
    <%= f.date_select :buy_date %><br>
  </p>

  <p>
    <%= f.label :shop %><br>
    <%= f.select :shop_id, options_for_select(@shops.map{ |s| [s.name, s.id] }, @bill.shop_id) %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/bills/edit.html.erb
<h1>Editing "<%= @bill.name %>" Bill</h1>

<%= render 'form' %>
 
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<h1>Listing bills</h1>

<%= link_to 'New bill', new_bill_path %>
 
<table>
  <tr>
    <th>Date</th>
    <th>Shop</th>
    <th>Amount</th>
    <th colspan="5">Options</th>
  </tr>
 
  <% @bills.each do |bill| %>
    <tr>
      <td><%= bill.buy_date.to_formatted_s(:month_day_year) %></td>
      <td><%= bill.shop.name %></td>
      <td><%= bill.amount %></td>
      <td><%= link_to 'Show products', bill_products_path(bill) %></td>
      <td><%= link_to 'Show bill', bill_path(bill) %></td>
      <td><%= link_to 'Edit', edit_bill_path(bill) %></td>
      <td><%= link_to 'Destroy', bill_path(bill),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/bills/new.html.erb
<h1>New Bill</h1>

<%= render 'form' %>
 
<%= link_to 'Back', bills_path %>

app/views/bills/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @bill.name %>
</p>

<p>
	<strong>Buy date:</strong> <%= @bill.buy_date %>
</p>

<p>
	<strong>Shop:</strong> <%= @bill.shop.name %>
</p>

<%= link_to 'Show Products', bill_products_path(@bill) %> |
<%= link_to 'Edit bill', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mybill</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to 'Shops', shops_url %>
<%= link_to 'Bills', bills_url %>
<%= link_to 'Products', products_url %>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
 
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@product.errors.count, "error") %> prohibited
        this product from being saved:
      </h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
  </p>

  <p>
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity, :step => 'any' %><br>
  </p>

  <p>
    <%= f.label :quantity_type %><br>
    <%= f.text_field :quantity_type %><br>
  </p>

  <p>
    <%= f.label :price %><br>
    <%= f.number_field :price, :step => 'any' %><br>
  </p>

  <p>
    <%= f.label :bill %><br>
    <%= f.select :bill_id, options_for_select(@bills.map{ |s| [s.shop.name + ' - ' + s.buy_date.to_formatted_s(:month_day_year), s.id] }, @product.bill_id) %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/products/edit.html.erb
<h1>Editing "<%= @product.name %>" Product</h1>

<%= render 'form' %>
 
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing Products</h1>

<%= link_to 'New product', new_product_path %>
 
<table>
  <tr>
    <th>Name</th>
    <th>Quantity</th>
    <th>Quantity Type</th>
    <th>Price</th>
    <th>Bill</th>
    <th>Shop</th>
    <th colspan="4">Options</th>
  </tr>
 
  <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.quantity %></td>
      <td><%= product.quantity_type %></td>
      <td><%= product.price %></td>
      <td><%= link_to product.bill.buy_date.to_formatted_s(:month_day_year), bill_path(product.bill) %></td>
      <td><%= link_to product.bill.shop.name, shop_path(product.bill.shop) %></td>
      <td><%= link_to 'Show', product_path(product) %></td>
      <td><%= link_to 'Edit', edit_product_path(product) %></td>
      <td><%= link_to 'Destroy', product_path(product),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>
 
<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
	<strong>Quantity:</strong> <%= @product.quantity %>
</p>

<p>
	<strong>Quantity Type:</strong> <%= @product.quantity_type %>
</p>

<p>
	<strong>Price:</strong> <%= @product.price %>€
</p>

<p>
	<strong>Bill:</strong> <%= @product.bill.shop.name + ' - ' + @product.bill.buy_date.to_formatted_s(:month_day_year) %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/shops/_form.html.erb
<%= form_for @shop do |f| %>
 
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@shop.errors.count, "error") %> prohibited
        this shop from being saved:
      </h2>
      <ul>
        <% @shop.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/shops/edit.html.erb
<h1>Editing "<%= @shop.name %>" Shop</h1>

<%= render 'form' %>
 
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<h1>Listing shops</h1>

<%= link_to 'New shop', new_shop_path %>
 
<table>
  <tr>
    <th>Name</th>
    <th>Amount</th>
    <th colspan="4">Options</th>
  </tr>
 
  <% @shops.each do |shop| %>
    <tr>
      <td><%= shop.name %></td>
      <td><%= shop.amount %></td>
      <td><%= link_to 'Shop bills', shop_bills_path(shop) %></td>
      <td><%= link_to 'Show', shop_path(shop) %></td>
      <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
      <td><%= link_to 'Destroy', shop_path(shop),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= render 'form' %>
 
<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @shop.name %>
</p>
<%= link_to 'Show bills', shop_bills_path(@shop) %> |
<%= link_to 'Edit shop', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>